Refactor, setting a boolean if and only if a socket is bound.

diff --git a/script/run-test-programs b/script/run-test-programs
--- a/script/run-test-programs
+++ b/script/run-test-programs
@@ -6,7 +6,9 @@ run_test_program() (
     case "$basename" in
 	(test-*)
 	    cd "$(dirname "$filename")"
-	    ${valgrind:+$valgrind }"./$basename" >"$basename.log"
+	    if ! ${valgrind:+$valgrind }"./$basename" >"$basename.log"; then
+		printf 'Test program %s failed' $basename
+	    fi
 	    ;;
 	(*)
 	    ;;
